# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               G.A. Joe
tagline:             'Google Analytics Productivity Tool For Businesses'
description:         'Most important metrics with context, target and alerts.'
url:                 http://blog.gajoe.co
baseurl:             http://blog.gajoe.co
paginate:            5

# About/contact
author:
  name:              G.A. Joe
  url:               https://twitter.com/gajoeapp
  email:             hello@gajoe.co

# Custom vars
version:             1.0.0
